meta_product_name: "Mindseed"
meta_title: "Mindseed - growing to your full potential"
meta_description: "Mindseed is the perfect helper for people willing to learn on the long term"
meta_image: "favicon_mindseed.png" # should exist in `app/assets/images/`
